#!/bin/bash

if [ -z "$1" ]
then
  echo "Error: You must provide a commit message."
  echo "Usage: gpush 'feat: my awesome feature'"
  exit 1
fi

git add .
git commit -m "$1"
git push

echo "🚀 Done! Everything is pushed."